import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validate } from '../index';
import { allSchemas } from '../schemaRegistry/schemaMap';

// llms.txt and llms-full.txt are what an LLM reads instead of the website,
// which renders client-side and so serves an empty page to anything that does
// not run JavaScript. They are generated by website/scripts/generate-llms.ts
// and shipped both on the site and inside the npm package.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const read = (name: string): string => readFileSync(join(REPO_ROOT, name), 'utf8');

const PTML_BLOCK = /```ptml\n([\s\S]*?)```/g;

const INDEX_FILE = 'llms.txt';
const FULL_FILE = 'llms-full.txt';

describe('generated LLM documentation', () => {
  it('is present at the package root and in the site public directory', () => {
    for (const name of [INDEX_FILE, FULL_FILE]) {
      expect(existsSync(join(REPO_ROOT, name))).toBe(true);
      expect(existsSync(join(REPO_ROOT, 'website', 'public', name))).toBe(true);
    }
  });

  it('ships identical copies in both places', () => {
    for (const name of [INDEX_FILE, FULL_FILE]) {
      expect(read(name)).toBe(read(join('website', 'public', name)));
    }
  });

  it('documents every node the language actually has', () => {
    const full = read(FULL_FILE);
    const missing = allSchemas.filter((schema) => !full.includes(`### \`${schema.name}\``));
    expect(missing.map((schema) => schema.name)).toEqual([]);
  });

  // The whole point of these files is that an LLM reads them and writes PTML
  // from them, so an example that does not validate teaches broken syntax.
  it('contains only examples that are valid PTML', () => {
    const blocks = [...read(FULL_FILE).matchAll(PTML_BLOCK)].map((match) => match[1]);
    expect(blocks.length).toBeGreaterThan(0);

    const failures = blocks
      .map((block) => ({ block, result: validate(block) }))
      .filter(({ result }) => !result.isValid)
      .map(({ block, result }) => `${block.trim().split('\n')[0]} -- ${!result.isValid && result.errorMessage}`);

    expect(failures).toEqual([]);
  });

  it('points at the plain-text docs from the README, which is what people paste at an LLM', () => {
    const readme = read('README.md');
    expect(readme).toContain(INDEX_FILE);
    expect(readme).toContain(FULL_FILE);
  });

  // The README example is the first PTML most people ever see.
  it('has a README whose PTML example is valid', () => {
    const blocks = [...read('README.md').matchAll(/```tsx\n([\s\S]*?)```/g)].map((match) => match[1]);
    const embedded = blocks.flatMap((block) => [...block.matchAll(/`\n([\s\S]*?)`;/g)].map((m) => m[1]));
    expect(embedded.length).toBeGreaterThan(0);

    embedded.forEach((ptml) => {
      const result = validate(ptml);
      expect(result.isValid ? true : result.errorMessage).toBe(true);
    });
  });

  it('tells the reader why the website itself cannot be read', () => {
    expect(read(INDEX_FILE)).toContain('rendered in the browser');
  });
});
